"""empty message

Revision ID: 02d6419126d9
Revises: 8d7f01e2ecf0
Create Date: 2024-10-02 16:36:39.855758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d6419126d9'
down_revision = '8d7f01e2ecf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=False, server_default="0")) # Remove server_default="0" after table update.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
