"""empty message

Revision ID: 0f664a1965ca
Revises: 
Create Date: 2023-01-09 23:59:29.456342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f664a1965ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('agent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone_num', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone_num')
    )
    op.create_table('batch_time',
    sa.Column('batch_time_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('batch_time_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('branch',
    sa.Column('branch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('branch_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city',
    sa.Column('city_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('city_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dial_code', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('source',
    sa.Column('source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lead',
    sa.Column('lead_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone_num', sa.Text(), nullable=False),
    sa.Column('alternate_phone_num', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('lead_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('batch_time_id', sa.Integer(), nullable=False),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('next_action_remarks', sa.Text(), nullable=True),
    sa.Column('details_sent', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('pitch_by', sa.Text(), nullable=True),
    sa.Column('demo_date', sa.Date(), nullable=True),
    sa.Column('instructor', sa.Text(), nullable=True),
    sa.Column('broadcast', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('fee_offer', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.agent_id'], ),
    sa.ForeignKeyConstraint(['batch_time_id'], ['batch_time.batch_time_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone_num', sa.Text(), nullable=False),
    sa.Column('alternate_phone_num', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('batch_time_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('total_fee', sa.Integer(), nullable=False),
    sa.Column('total_fee_paid', sa.Integer(), nullable=False),
    sa.Column('total_pending_fee', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_time_id'], ['batch_time.batch_time_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['agent.agent_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('receipt',
    sa.Column('receipt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('installment_payment', sa.Integer(), nullable=True),
    sa.Column('installment_payment_mode', sa.Enum('cash', 'debit_card', 'credit_card', 'upi', name='paymentmode'), nullable=True),
    sa.Column('installment_payment_date', sa.Date(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt')
    op.drop_table('student')
    op.drop_table('lead')
    op.drop_table('source')
    op.drop_table('course')
    op.drop_table('country')
    op.drop_table('city')
    op.drop_table('branch')
    op.drop_table('batch_time')
    op.drop_table('agent')
    # ### end Alembic commands ###
