"""empty message

Revision ID: 23ba74672699
Revises: 97235434d955
Create Date: 2023-01-28 23:00:29.597320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23ba74672699'
down_revision = '97235434d955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_modules', sa.Text(), nullable=True))
        batch_op.drop_column('json_module')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_module', mysql.TEXT(), nullable=True))
        batch_op.drop_column('json_modules')

    # ### end Alembic commands ###
