"""empty message

Revision ID: 27e96dae6b7b
Revises: a40f748165a2
Create Date: 2023-01-27 12:21:52.683646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27e96dae6b7b'
down_revision = 'a40f748165a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_status', sa.Integer(), nullable=False))
        batch_op.drop_column('is_student')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_student', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('admission_status')

    # ### end Alembic commands ###
