"""empty message

Revision ID: 2b555b060e2c
Revises: 4a370dc0d831
Create Date: 2023-01-27 19:06:06.189720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b555b060e2c'
down_revision = '4a370dc0d831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_num', sa.Enum('first', 'second', 'third', 'fourth', name='instalmentnumber'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('installment_num')

    # ### end Alembic commands ###
