"""empty message

Revision ID: 2cac18908602
Revises: 94f82524f940
Create Date: 2023-06-10 12:50:02.417698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cac18908602'
down_revision = '94f82524f940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who_you_are', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('who_you_are')

    # ### end Alembic commands ###
