"""empty message

Revision ID: 2ef70da0463c
Revises: b8e79dfcaed6
Create Date: 2024-01-26 16:14:52.450973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef70da0463c'
down_revision = 'b8e79dfcaed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_category',
    sa.Column('course_category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('course_category_id'),
    sa.UniqueConstraint('name')
    )

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('course_category', 'course_category', ['course_category_id'], ['course_category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('course_category', type_='foreignkey')
        batch_op.drop_column('course_category_id')

    op.drop_table('course_category')
    # ### end Alembic commands ###
