"""empty message

Revision ID: 32973fe7d5a6
Revises: 5a4099746edc
Create Date: 2023-04-20 15:32:52.800472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32973fe7d5a6'
down_revision = '5a4099746edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reason_to_join', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('who_is', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lead_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('lead_status')
        batch_op.drop_column('who_is')
        batch_op.drop_column('reason_to_join')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
