"""empty message

Revision ID: 346b64fcfbb1
Revises: 3833a5f4cdd2
Create Date: 2025-06-24 21:48:03.715391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346b64fcfbb1'
down_revision = '3833a5f4cdd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignment_date', sa.Date(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('json_batch_ids', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('is_assigned_to_students', sa.Integer(), nullable=False, default=1),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.trainer_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment')
    # ### end Alembic commands ###
