"""empty message

Revision ID: 3c1802972d2c
Revises: a091a525e479
Create Date: 2023-06-10 11:03:19.273121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1802972d2c'
down_revision = 'a091a525e479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trainer_id', sa.Integer(), nullable=True))
        # batch_op.drop_constraint('agent_id', type_='foreignkey')
        batch_op.create_foreign_key('agent', 'agent', ['agent_id'], ['agent_id'])
        batch_op.create_foreign_key('state', 'state', ['state_id'], ['state_id'])
        batch_op.create_foreign_key('trainer', 'trainer', ['trainer_id'], ['trainer_id'])
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('agent', type_='foreignkey')
        batch_op.drop_constraint('state', type_='foreignkey')
        batch_op.drop_constraint('trainer', type_='foreignkey')
        batch_op.drop_column('trainer_id')
        batch_op.drop_column('agent_id')
        batch_op.drop_column('state_id')

    # ### end Alembic commands ###
