"""empty message

Revision ID: 415f1d06f432
Revises: 5128288592ef
Create Date: 2023-02-07 22:50:41.328965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '415f1d06f432'
down_revision = '5128288592ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_content',
    sa.Column('course_content_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('instructor_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('json_modules', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('course_content_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('json_modules')
        batch_op.drop_column('instructor_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('json_modules', mysql.TEXT(), nullable=True))

    op.drop_table('course_content')
    # ### end Alembic commands ###
