"""empty message

Revision ID: 4a370dc0d831
Revises: ec64d0d890a4
Create Date: 2023-01-27 18:14:28.393920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a370dc0d831'
down_revision = 'ec64d0d890a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_payment_transaction_number', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('installment_payment_transaction_number')

    # ### end Alembic commands ###
