"""empty message

Revision ID: 575130950e17
Revises: e194e66d1b5a
Create Date: 2023-02-02 23:52:35.654251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575130950e17'
down_revision = 'e194e66d1b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
