"""empty message

Revision ID: 5777a4169ea0
Revises: 7bdc8358c1a6
Create Date: 2023-01-31 08:16:17.702048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5777a4169ea0'
down_revision = '7bdc8358c1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_image_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('back_image_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('passport_image_path', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('passport_image_path')
        batch_op.drop_column('back_image_path')
        batch_op.drop_column('front_image_path')

    # ### end Alembic commands ###
