"""empty message

Revision ID: 5c049a37fc15
Revises: 1599f70ae270
Create Date: 2024-12-15 18:21:24.311433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c049a37fc15'
down_revision = '1599f70ae270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
        sa.Column('attendance_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('lecture_id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('attendance_status', sa.Integer(), nullable=False),
        sa.Column('deleted', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['lecture_id'], ['lecture.lecture_id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
        sa.PrimaryKeyConstraint('attendance_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
