"""empty message

Revision ID: 64014bc431a4
Revises: 814936cb8546
Create Date: 2023-08-27 18:21:07.929284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64014bc431a4'
down_revision = '814936cb8546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('seats_occupied', sa.Integer(), nullable=False),
    sa.Column('seats_vacant', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('batch_time_id', sa.Integer(), nullable=False),
    sa.Column('course_mode_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_time_id'], ['batch_time.batch_time_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['course_mode_id'], ['course_mode.course_mode_id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.trainer_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch')
    # ### end Alembic commands ###
