"""empty message

Revision ID: 6d4a281388a5
Revises: d38788292ce6
Create Date: 2023-08-01 23:16:48.804326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4a281388a5'
down_revision = 'd38788292ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submitted_lead',
    sa.Column('submitted_lead_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone_num', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('hash_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('referer', sa.VARCHAR(length=255), nullable=True),
    sa.Column('referer_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('form_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_ip', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), nullable=True),
    sa.Column('actions_count', sa.Integer(), nullable=True),
    sa.Column('actions_succeeded_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), nullable=True),
    sa.Column('submitted_status', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at_gmt', sa.DateTime(), nullable=True),
    sa.Column('updated_at_gmt', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('submitted_lead_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitted_lead')
    # ### end Alembic commands ###
