"""empty message

Revision ID: 7908be30feac
Revises: fda9186552db
Create Date: 2024-05-12 06:49:06.600371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7908be30feac'
down_revision = 'fda9186552db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_content_class_recording_id', sa.Integer(), nullable=False, default=1))
        batch_op.add_column(sa.Column('json_course_learning_progress_class_recording', sa.Text(), nullable=True))
        batch_op.create_foreign_key('course_content_class_recording', 'course_content_class_recording', ['course_content_class_recording_id'], ['course_content_class_recording_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('course_content_class_recording', type_='foreignkey')
        batch_op.drop_column('json_course_learning_progress_class_recording')
        batch_op.drop_column('course_content_class_recording_id')

    # ### end Alembic commands ###
