"""empty message

Revision ID: 7988193d98be
Revises: cfc8aaa7d35a
Create Date: 2023-01-28 20:38:28.674292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7988193d98be'
down_revision = 'cfc8aaa7d35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
