"""empty message

Revision ID: 7bdc8358c1a6
Revises: 23ba74672699
Create Date: 2023-01-31 08:12:27.602479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdc8358c1a6'
down_revision = '23ba74672699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('area', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('highest_education', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('purpose_for_course', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('referred_by')
        batch_op.drop_column('purpose_for_course')
        batch_op.drop_column('occupation')
        batch_op.drop_column('highest_education')
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')
        batch_op.drop_column('area')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
