"""empty message

Revision ID: 814936cb8546
Revises: c424741ce48a
Create Date: 2023-08-11 16:26:06.712244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814936cb8546'
down_revision = 'c424741ce48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('lead_time')
    # ### end Alembic commands ###
