"""empty message

Revision ID: 8981fc6277f2
Revises: ab6a60bf54c9
Create Date: 2023-12-10 17:37:55.187166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8981fc6277f2'
down_revision = 'ab6a60bf54c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('course_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('course', 'course', ['course_id'], ['course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('course_content', schema=None) as batch_op:
        batch_op.drop_constraint('course', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
