"""empty message

Revision ID: 95a666303d95
Revises: 32973fe7d5a6
Create Date: 2023-04-20 20:32:31.982541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a666303d95'
down_revision = '32973fe7d5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state_id'),
    sa.UniqueConstraint('name')
    )

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('state', 'state', ['state_id'], ['state_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_constraint('state', type_='foreignkey')
        batch_op.drop_column('state_id')

    op.drop_table('state')
    # ### end Alembic commands ###
