"""empty message

Revision ID: 97235434d955
Revises: 7988193d98be
Create Date: 2023-01-28 22:59:40.205565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97235434d955'
down_revision = '7988193d98be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('json_module', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('json_module')
        batch_op.drop_column('instructor_name')

    # ### end Alembic commands ###
