"""empty message

Revision ID: 981dc6fbe43b
Revises: 9b73ffed8188
Create Date: 2023-02-01 22:05:35.790850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981dc6fbe43b'
down_revision = '9b73ffed8188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_course_learning_progress', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('json_course_learning_progress')

    # ### end Alembic commands ###
