"""empty message

Revision ID: 9b73ffed8188
Revises: 5777a4169ea0
Create Date: 2023-01-31 21:06:29.306145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b73ffed8188'
down_revision = '5777a4169ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_document_verified', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('is_document_verified')

    # ### end Alembic commands ###
