"""empty message

Revision ID: a091a525e479
Revises: 95a666303d95
Create Date: 2023-04-25 08:35:48.923998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a091a525e479'
down_revision = '95a666303d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer',
    sa.Column('trainer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone_num', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('trainer_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_num')
    )

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('trainer', 'trainer', ['trainer_id'], ['trainer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_constraint('trainer', type_='foreignkey')
        batch_op.drop_column('trainer_id')

    op.drop_table('trainer')
    # ### end Alembic commands ###
