"""empty message

Revision ID: a3406268c113
Revises: 712fafc7588b
Create Date: 2023-02-20 22:43:44.032472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3406268c113'
down_revision = '712fafc7588b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['lead_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lead_id')

    # ### end Alembic commands ###
