"""empty message

Revision ID: ab6a60bf54c9
Revises: bfd8606f0dcf
Create Date: 2023-09-23 19:50:12.720403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6a60bf54c9'
down_revision = 'bfd8606f0dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr',
    sa.Column('hr_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone_num', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('hr_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_num')
    )
    op.create_table('placement',
    sa.Column('placement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('joined_course_for', sa.VARCHAR(length=255), nullable=True),
    sa.Column('education', sa.VARCHAR(length=255), nullable=True),
    sa.Column('technical_knowledge', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project', sa.VARCHAR(length=255), nullable=True),
    sa.Column('mock_test', sa.VARCHAR(length=255), nullable=True),
    sa.Column('test', sa.VARCHAR(length=255), nullable=True),
    sa.Column('communication', sa.VARCHAR(length=255), nullable=True),
    sa.Column('preferred_location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('placement_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement')
    op.drop_table('hr')
    # ### end Alembic commands ###
