"""empty message

Revision ID: b7fe2655f01b
Revises: 2ef70da0463c
Create Date: 2024-02-11 20:10:04.037612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fe2655f01b'
down_revision = '2ef70da0463c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('resume_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_profile_picture', sa.VARCHAR(length=255), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone_num', sa.VARCHAR(length=255), nullable=True),
    sa.Column('alternate_phone_num', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('area', sa.VARCHAR(length=255), nullable=True),
    sa.Column('hometown', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.Column('linkedin_link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('job_role', sa.VARCHAR(length=255), nullable=True),
    sa.Column('about_me', sa.VARCHAR(length=255), nullable=True),
    sa.Column('skill', sa.Text(), nullable=True),
    sa.Column('tool', sa.Text(), nullable=True),
    sa.Column('project_name_1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_link_1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_task_done_1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_name_2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_link_2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_task_done_2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_name_3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_link_3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_task_done_3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_name_4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_link_4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_task_done_4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('class_10_school_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('class_10_passed_out_year', sa.VARCHAR(length=255), nullable=True),
    sa.Column('class_12_school_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('class_12_passed_out_year', sa.VARCHAR(length=255), nullable=True),
    sa.Column('graduation_college_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('graduation_college_passed_out_year', sa.VARCHAR(length=255), nullable=True),
    sa.Column('post_graduation_college_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('post_graduation_college_passed_out_year', sa.VARCHAR(length=255), nullable=True),
    sa.Column('certificate_name_1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('certificate_passed_out_year_1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('certificate_name_2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('certificate_passed_out_year_2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('certificate_name_3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('certificate_passed_out_year_3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('certificate_name_4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('certificate_passed_out_year_4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('resume_id'),
    sa.UniqueConstraint('alternate_phone_num'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('linkedin_link'),
    sa.UniqueConstraint('phone_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('resume')
    # ### end Alembic commands ###
