"""empty message

Revision ID: b8e79dfcaed6
Revises: 8981fc6277f2
Create Date: 2024-01-11 21:17:48.479125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e79dfcaed6'
down_revision = '8981fc6277f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
   sa.Column('call_logs_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('phone_num', sa.VARCHAR(length=255), nullable=True),
            sa.Column('call_time', sa.DateTime(), nullable=True),
            sa.Column('call_time_duration', sa.VARCHAR(length=255), nullable=True),
            sa.Column('call_type', sa.VARCHAR(length=255), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
            sa.PrimaryKeyConstraint('call_logs_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('call_logs')
    # ### end Alembic commands ###
