"""empty message

Revision ID: c424741ce48a
Revises: 10d5755751d3
Create Date: 2023-08-08 23:19:22.857619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c424741ce48a'
down_revision = '10d5755751d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('agent', 'agent', ['agent_id'], ['agent_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_lead', schema=None) as batch_op:
        batch_op.drop_constraint('agent_id', type_='foreignkey')
        batch_op.drop_column('agent_id')
        batch_op.drop_column('remark')
    # ### end Alembic commands ###
