"""empty message

Revision ID: c931fa625e79
Revises: 6d4a281388a5
Create Date: 2023-08-05 11:32:13.806884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c931fa625e79'
down_revision = '6d4a281388a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_insertion_mechanism_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('lead_insertion_mechanism_type')
    # ### end Alembic commands ###
