"""empty message

Revision ID: c976cd525beb
Revises: 2b555b060e2c
Create Date: 2023-01-27 19:27:40.372638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c976cd525beb'
down_revision = '2b555b060e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.alter_column('installment_num',
               existing_type=mysql.ENUM('first', 'second', 'third', 'fourth'),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.alter_column('installment_num',
               existing_type=sa.Integer(),
               type_=mysql.ENUM('first', 'second', 'third', 'fourth'),
               existing_nullable=True)

    # ### end Alembic commands ###
