"""empty message

Revision ID: cfc8aaa7d35a
Revises: 559ee82d72d8
Create Date: 2023-01-28 19:16:48.565830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc8aaa7d35a'
down_revision = '559ee82d72d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
