"""empty message

Revision ID: ec64d0d890a4
Revises: 27e96dae6b7b
Create Date: 2023-01-27 17:41:20.037334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec64d0d890a4'
down_revision = '27e96dae6b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_mode',
    sa.Column('payment_mode_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('payment_mode_id')
    )
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_payment_mode_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'payment_mode', ['installment_payment_mode_id'], ['payment_mode_id'])
        batch_op.drop_column('installment_payment_mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_payment_mode', mysql.ENUM('cash', 'debit_card', 'credit_card', 'upi'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('installment_payment_mode_id')

    op.drop_table('payment_mode')
    # ### end Alembic commands ###
