"""empty message

Revision ID: f3a7c2c2bc32
Revises: 7908be30feac
Create Date: 2024-05-28 18:37:02.688852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a7c2c2bc32'
down_revision = '7908be30feac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('course_content_class_recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('batch', 'batch', ['batch_id'], ['batch_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('course_content_class_recording', schema=None) as batch_op:
        batch_op.drop_constraint('batch', type_='foreignkey')
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
