"""empty message

Revision ID: f96208a10135
Revises: 59db4d015a68
Create Date: 2024-05-28 21:29:38.957337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96208a10135'
down_revision = '59db4d015a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('course_content_class_recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('course_content_class_recording', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
