"""empty message

Revision ID: fda9186552db
Revises: 7f39ea2cc568
Create Date: 2024-05-03 22:58:24.507842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda9186552db'
down_revision = '7f39ea2cc568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_content_class_recording',
    sa.Column('course_content_class_recording_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('instructor_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('json_modules', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('course_content_class_recording_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_content_class_recording')
    # ### end Alembic commands ###
