"""empty message

Revision ID: fde3b50f1591
Revises: e2bfde987da5
Create Date: 2023-04-09 10:18:54.430968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde3b50f1591'
down_revision = 'e2bfde987da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_mode',
    sa.Column('course_mode_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('course_mode_id'),
    sa.UniqueConstraint('name')
    )

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_mode_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('course_mode', 'course_mode', ['course_mode_id'], ['course_mode_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_constraint('course_mode', type_='foreignkey')
        batch_op.drop_column('course_mode_id')

    op.drop_table('course_mode')
    # ### end Alembic commands ###
